### PR TITLE
Restructure the package to use the Crypt package

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

- Removes hardcoded OpenSSL dependency in favor of using our Crypt package
- Removes the `KeychainManager` utility as we won't be able to reliably be able to build the Crypt object that the Keychain will be dependent upon

### CODE REVIEW

**Comment by mbabker** [comment]
@wilsonge For the shape it's in now this is ready for review/merge.

**Comment by mbabker** [comment]
Ping @wilsonge

**Comment by wilsonge** [comment]
Is there a reason we can't ship a `CipherInterface` implementation in this package so that existing legacy keychains can be used/validated?

**Comment by mbabker** [comment]
When we get an OpenSSL cipher into the Crypt package that would cover it.

**Comment by wilsonge** [comment]
Crypto to an extent is an OpenSSL wrapper? But we won't use an IV of `1234567890123456` in the main Crypt Package right? It will be random bytes

**Comment by mbabker** [comment]
Crypto is mcrypt based.

We won't have a hardcoded IV.  Probably something that can be injected with a default fallback.  Still have to work out the exact details.

**Comment by wilsonge** [comment]
Are you sure? I mean I only gave it a quick glance over but.... https://github.com/defuse/php-encryption/blob/v2.1.0/src/Crypto.php#L326

**Comment by mbabker** [comment]
Hmm, guess it is.  I remember the test class for that cipher failing on PHP 7.2 and I took it to be an mcrypt related thing.  Honestly, I hadn't dug into it much at all.

**Comment by wilsonge** [comment]
I mean I'm happy with this in principle but I'd like for there to be a built in way to keep working with the existing keychain unless there's a really good reason not to (which I don't think there is - it's just a matter of doing the implementation)

**Comment by mbabker** [comment]
1) We create our OpenSSL crypt cipher and it be configurable in the same ways that the current class allows (injecting IV and method), or if it is possible to use the CryptoCipher and do this work even better
2) Providing docs on how to push the right stuff into the cipher, main Crypt class, and the Key object

Otherwise, the APIs aren't 1-for-1 compatible.  So I mean I'm sure there's a way to do it, I just haven't sorted out the how of it yet.

**Comment by wilsonge** [comment]
I agree that's fine. But I think let's have that code done before we merge this in

**Pull request merged**
